name: Android Feature Branch CI

on: pull_request

jobs:
  pull_request:
    name: Build with Gradle
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8
      - name: Spotless
        run: bash ./gradlew spotlessCheck
      - name: Build with Gradle
        run: bash ./gradlew assembleDebug assembleDebugAndroidTest
      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 2
      - name: Upload Espresso APK
        uses: actions/upload-artifact@v2
        with:
          name: espresso
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
          retention-days: 2
