name: Pull Request CI
on: pull_request
jobs:
  cancel-old-workflows:
    name: Cancel Old Workflows
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Cancel Old Workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: update-screenshots-baseline.yml,pull-request.yml
          access_token: ${{ github.token }}

  spotless:
    name: Spotless
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Spotless
        run: ./gradlew spotlessCheck
        working-directory: .

  unit-tests:
    name: Unit tests
    needs: spotless
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Unit tests
        run: ./gradlew testDebugUnitTest
        working-directory: .

  instrumentation-tests:
    name: Instrumentation tests
    needs: spotless
    runs-on: macOS-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        api-level: [26]
    steps:
      - uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          script: |
            adb logcat > logcat.out &
            ./gradlew connectedCheck --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-${{ matrix.api-level }}
          path: '**/build/reports'

      - name: Upload logcat
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logcat-${{ matrix.api-level }}
          path: logcat.out
